POST https://aprendendo-nodejs-5x40.onrender.com/videos
content-type: application/json

{
    "title":"video",
    "description":"primeiro video de Node",
    "duration":1000
}

###

GET https://aprendendo-nodejs-5x40.onrender.com/videos

###

PUT https://aprendendo-nodejs-5x40.onrender.com/videos/f5b13de6-1352-4a92-b0b6-a8918e09d5fd
content-type: application/json

{
    "title":"video novo",
    "description":"segundo video",
    "duration":1000
}

###

DELETE https://aprendendo-nodejs-5x40.onrender.com/videos/3598627e-95e5-478b-a347-f4113e8bfdca
