POST http://localhost:3000/videos HTTP/1.1
content-type: application/json

{
    "title":"video Node",
    "description":"primeiro video de Node",
    "duration":1000
}

###

GET http://localhost:3000/videos

###

PUT http://localhost:3000/videos/f5b13de6-1352-4a92-b0b6-a8918e09d5fd
content-type: application/json

{
    "title":"video novo",
    "description":"segundo video",
    "duration":1000
}

###

DELETE http://localhost:3000/videos/3598627e-95e5-478b-a347-f4113e8bfdca
